sudo: false
language: python
matrix:
  include:
    - os: linux
      python: 3.5
      env: TOX_ENV=py35
    - os: linux
      python: 3.6
      env: TOX_ENV=py36
    - os: linux
      python: 3.6
      env: TOX_ENV=flake8

install:
  - pip install tox

script: tox -e $TOX_ENV
